application: photpmanias
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /assets
  static_dir: assets
- url: /gallery
  static_dir: gallery

- url: /pixastic
  static_dir: pixastic  
- url: /buttoncustem
  static_dir: buttoncustem



- url: /.*
  script: YourAlbum.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

